spring.application.name=AIMS_Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/aims_db
spring.datasource.username=aims_app
spring.datasource.password=group03AITSS
spring.jpa.properties.hibernate.default_schema=aims

# show sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# log sql query
logging.level.org.hibernate.SQL=DEBUG

# log parameter
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.default_schema=aims
